INSERT INTO roles(`name`) VALUES('ROLE_CASHIER');
INSERT INTO roles(`name`) VALUES('ROLE_MODERATOR');
INSERT INTO roles(`name`) VALUES('ROLE_ADMIN');
INSERT INTO roles(`name`) VALUES('ROLE_MECHANIC');